"""re-crea la tabla torneo_categoria

Revision ID: 0894aef0cfc3
Revises: bb787cdebde4
Create Date: 2025-06-25 19:12:47.402497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0894aef0cfc3'
down_revision: Union[str, None] = 'bb787cdebde4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('torneo_categoria',
    sa.Column('torneo_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['test_schema.categoria.id'], ),
    sa.ForeignKeyConstraint(['torneo_id'], ['test_schema.torneo.id'], ),
    sa.PrimaryKeyConstraint('torneo_id', 'categoria_id'),
    schema='test_schema'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('torneo_categoria', schema='test_schema')
    # ### end Alembic commands ###
