"""Clase Partido actualizado, con CRUD y Endpoints

Revision ID: 759121c13800
Revises: c5f00b1fa2dd
Create Date: 2025-06-26 22:50:22.808996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '759121c13800'
down_revision: Union[str, None] = 'c5f00b1fa2dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partido', sa.Column('equipo_ganador_id', sa.Integer(), nullable=True), schema='test_schema')
    op.add_column('partido', sa.Column('jugador_ganador_id', sa.Integer(), nullable=True), schema='test_schema')
    op.create_foreign_key(None, 'partido', 'equipo', ['equipo_ganador_id'], ['id'], source_schema='test_schema', referent_schema='test_schema')
    op.create_foreign_key(None, 'partido', 'jugador', ['jugador_ganador_id'], ['id'], source_schema='test_schema', referent_schema='test_schema')
    op.drop_column('partido', 'resultado', schema='test_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partido', sa.Column('resultado', sa.VARCHAR(), autoincrement=False, nullable=False), schema='test_schema')
    op.drop_constraint(None, 'partido', schema='test_schema', type_='foreignkey')
    op.drop_constraint(None, 'partido', schema='test_schema', type_='foreignkey')
    op.drop_column('partido', 'jugador_ganador_id', schema='test_schema')
    op.drop_column('partido', 'equipo_ganador_id', schema='test_schema')
    # ### end Alembic commands ###
