"""tablas q me faltaron

Revision ID: 807e1843b02e
Revises: b725aa043257
Create Date: 2025-07-06 16:11:59.339771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '807e1843b02e'
down_revision: Union[str, None] = 'b725aa043257'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genero', sa.Column('categoria_id', sa.Integer(), nullable=True), schema='test_schema')
    op.create_foreign_key(None, 'genero', 'categoria', ['categoria_id'], ['id'], source_schema='test_schema', referent_schema='test_schema')
    op.alter_column('jugador', 'genero',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               nullable=True,
               schema='test_schema')
    op.create_foreign_key(None, 'jugador', 'genero', ['genero'], ['id'], source_schema='test_schema', referent_schema='test_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jugador', schema='test_schema', type_='foreignkey')
    op.alter_column('jugador', 'genero',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               nullable=False,
               schema='test_schema')
    op.drop_constraint(None, 'genero', schema='test_schema', type_='foreignkey')
    op.drop_column('genero', 'categoria_id', schema='test_schema')
    # ### end Alembic commands ###
