"""crea torneo_categoria ahora con crud y router y la wea en el main

Revision ID: 939a746ae47a
Revises: 0894aef0cfc3
Create Date: 2025-06-25 21:55:10.150764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '939a746ae47a'
down_revision: Union[str, None] = '0894aef0cfc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
