"""Se agrega id a torneo_cateforia y se agrega tabla inscripcion

Revision ID: 9955bb636f71
Revises: 759121c13800
Create Date: 2025-06-27 19:29:16.768106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9955bb636f71'
down_revision: Union[str, None] = '759121c13800'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('torneo_categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('torneo_id', sa.Integer(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['test_schema.categoria.id'], ),
    sa.ForeignKeyConstraint(['torneo_id'], ['test_schema.torneo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='test_schema'
    )
    op.create_index(op.f('ix_test_schema_torneo_categoria_id'), 'torneo_categoria', ['id'], unique=False, schema='test_schema')
    op.create_table('inscripcion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jugador_id', sa.Integer(), nullable=True),
    sa.Column('equipo_id', sa.Integer(), nullable=True),
    sa.Column('torneo_categoria_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['equipo_id'], ['test_schema.equipo.id'], ),
    sa.ForeignKeyConstraint(['jugador_id'], ['test_schema.jugador.id'], ),
    sa.ForeignKeyConstraint(['torneo_categoria_id'], ['test_schema.torneo_categoria.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='test_schema'
    )
    op.create_index(op.f('ix_test_schema_inscripcion_id'), 'inscripcion', ['id'], unique=False, schema='test_schema')
    op.add_column('partido', sa.Column('resultado', sa.String(), nullable=False), schema='test_schema')
    op.drop_constraint('partido_jugador_ganador_id_fkey', 'partido', schema='test_schema', type_='foreignkey')
    op.drop_constraint('partido_equipo_ganador_id_fkey', 'partido', schema='test_schema', type_='foreignkey')
    op.drop_column('partido', 'equipo_ganador_id', schema='test_schema')
    op.drop_column('partido', 'jugador_ganador_id', schema='test_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partido', sa.Column('jugador_ganador_id', sa.INTEGER(), autoincrement=False, nullable=True), schema='test_schema')
    op.add_column('partido', sa.Column('equipo_ganador_id', sa.INTEGER(), autoincrement=False, nullable=True), schema='test_schema')
    op.create_foreign_key('partido_equipo_ganador_id_fkey', 'partido', 'equipo', ['equipo_ganador_id'], ['id'], source_schema='test_schema', referent_schema='test_schema')
    op.create_foreign_key('partido_jugador_ganador_id_fkey', 'partido', 'jugador', ['jugador_ganador_id'], ['id'], source_schema='test_schema', referent_schema='test_schema')
    op.drop_column('partido', 'resultado', schema='test_schema')
    op.drop_index(op.f('ix_test_schema_inscripcion_id'), table_name='inscripcion', schema='test_schema')
    op.drop_table('inscripcion', schema='test_schema')
    op.drop_index(op.f('ix_test_schema_torneo_categoria_id'), table_name='torneo_categoria', schema='test_schema')
    op.drop_table('torneo_categoria', schema='test_schema')
    # ### end Alembic commands ###
