"""10-07_N1_RevisionErrorIndesModels

Revision ID: a9b8fbb64d8c
Revises: af26324cba0a
Create Date: 2025-07-10 01:08:32.317703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9b8fbb64d8c'
down_revision: Union[str, None] = 'af26324cba0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mesa', sa.Column('torneo_id', sa.Integer(), nullable=True), schema='test_schema')
    op.drop_constraint('mesa_Torneo_id_fkey', 'mesa', schema='test_schema', type_='foreignkey')
    op.create_foreign_key(None, 'mesa', 'torneo', ['torneo_id'], ['id'], source_schema='test_schema', referent_schema='test_schema')
    op.drop_column('mesa', 'Torneo_id', schema='test_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mesa', sa.Column('Torneo_id', sa.INTEGER(), autoincrement=False, nullable=True), schema='test_schema')
    op.drop_constraint(None, 'mesa', schema='test_schema', type_='foreignkey')
    op.create_foreign_key('mesa_Torneo_id_fkey', 'mesa', 'torneo', ['Torneo_id'], ['id'], source_schema='test_schema', referent_schema='test_schema')
    op.drop_column('mesa', 'torneo_id', schema='test_schema')
    # ### end Alembic commands ###
