"""Se arreglan relationship y se agregan datos de prueba

Revision ID: b50da8fb0a7c
Revises: e4f5e7cee872
Create Date: 2025-06-20 02:04:53.982465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b50da8fb0a7c'
down_revision: Union[str, None] = 'e4f5e7cee872'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jugador', sa.Column('categoria_id', sa.Integer(), nullable=True), schema='test_schema')
    op.drop_constraint('jugador_ategoria_id_fkey', 'jugador', schema='test_schema', type_='foreignkey')
    op.create_foreign_key(None, 'jugador', 'categoria', ['categoria_id'], ['id'], source_schema='test_schema', referent_schema='test_schema')
    op.drop_column('jugador', 'ategoria_id', schema='test_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jugador', sa.Column('ategoria_id', sa.INTEGER(), autoincrement=False, nullable=True), schema='test_schema')
    op.drop_constraint(None, 'jugador', schema='test_schema', type_='foreignkey')
    op.create_foreign_key('jugador_ategoria_id_fkey', 'jugador', 'categoria', ['ategoria_id'], ['id'], source_schema='test_schema', referent_schema='test_schema')
    op.drop_column('jugador', 'categoria_id', schema='test_schema')
    # ### end Alembic commands ###
