"""Nueva forma de Fase

Revision ID: b5b7d0e12565
Revises: 624b444940fd
Create Date: 2025-06-29 18:04:20.505401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5b7d0e12565'
down_revision: Union[str, None] = '624b444940fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fase', sa.Column('torneo_categoria_id', sa.Integer(), nullable=True), schema='test_schema')
    op.drop_constraint('fase_Torneo_id_fkey', 'fase', schema='test_schema', type_='foreignkey')
    op.create_foreign_key(None, 'fase', 'torneo_categoria', ['torneo_categoria_id'], ['id'], source_schema='test_schema', referent_schema='test_schema')
    op.drop_column('fase', 'Torneo_id', schema='test_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fase', sa.Column('Torneo_id', sa.INTEGER(), autoincrement=False, nullable=True), schema='test_schema')
    op.drop_constraint(None, 'fase', schema='test_schema', type_='foreignkey')
    op.create_foreign_key('fase_Torneo_id_fkey', 'fase', 'torneo', ['Torneo_id'], ['id'], source_schema='test_schema', referent_schema='test_schema')
    op.drop_column('fase', 'torneo_categoria_id', schema='test_schema')
    # ### end Alembic commands ###
