"""Se devuelve DateTime a Time porque no me sirvio alembicdowngrade -1

Revision ID: bb787cdebde4
Revises: bd8162787d2f
Create Date: 2025-06-20 17:03:11.382532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb787cdebde4'
down_revision: Union[str, None] = 'bd8162787d2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
