"""no funco

Revision ID: c7eeca16583e
Revises: b00b5af325c8
Create Date: 2025-07-08 00:47:57.307513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7eeca16583e'
down_revision: Union[str, None] = 'b00b5af325c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('edad_Min', sa.Integer(), nullable=True),
    sa.Column('edad_Max', sa.Integer(), nullable=True),
    sa.Column('set_por_partido', sa.Integer(), nullable=True),
    sa.Column('puntos_por_set', sa.Integer(), nullable=True),
    sa.Column('genero', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='test_schema'
    )
    op.create_index(op.f('ix_test_schema_categoria_id'), 'categoria', ['id'], unique=False, schema='test_schema')
    op.create_table('genero',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='test_schema'
    )
    op.create_index(op.f('ix_test_schema_genero_id'), 'genero', ['id'], unique=False, schema='test_schema')
    op.create_table('pais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='test_schema'
    )
    op.create_index(op.f('ix_test_schema_pais_id'), 'pais', ['id'], unique=False, schema='test_schema')
    op.create_table('torneo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('fecha_Inscripcion', sa.Date(), nullable=False),
    sa.Column('competencia', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='test_schema'
    )
    op.create_index(op.f('ix_test_schema_torneo_id'), 'torneo', ['id'], unique=False, schema='test_schema')
    op.create_table('ciudad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('pais', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pais'], ['test_schema.pais.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='test_schema'
    )
    op.create_index(op.f('ix_test_schema_ciudad_id'), 'ciudad', ['id'], unique=False, schema='test_schema')
    op.create_table('mesa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Torneo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Torneo_id'], ['test_schema.torneo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='test_schema'
    )
    op.create_table('torneo_categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('torneo_id', sa.Integer(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['test_schema.categoria.id'], ),
    sa.ForeignKeyConstraint(['torneo_id'], ['test_schema.torneo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='test_schema'
    )
    op.create_index(op.f('ix_test_schema_torneo_categoria_id'), 'torneo_categoria', ['id'], unique=False, schema='test_schema')
    op.create_table('asociacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('ciudad', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ciudad'], ['test_schema.ciudad.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='test_schema'
    )
    op.create_index(op.f('ix_test_schema_asociacion_id'), 'asociacion', ['id'], unique=False, schema='test_schema')
    op.create_table('fase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('torneo_categoria_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['torneo_categoria_id'], ['test_schema.torneo_categoria.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='test_schema'
    )
    op.create_index(op.f('ix_test_schema_fase_id'), 'fase', ['id'], unique=False, schema='test_schema')
    op.create_table('jugador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('genero', sa.Integer(), nullable=True),
    sa.Column('ciudad', sa.Integer(), nullable=True),
    sa.Column('asociacion_id', sa.Integer(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asociacion_id'], ['test_schema.asociacion.id'], ),
    sa.ForeignKeyConstraint(['categoria_id'], ['test_schema.categoria.id'], ),
    sa.ForeignKeyConstraint(['ciudad'], ['test_schema.ciudad.id'], ),
    sa.ForeignKeyConstraint(['genero'], ['test_schema.genero.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='test_schema'
    )
    op.create_index(op.f('ix_test_schema_jugador_id'), 'jugador', ['id'], unique=False, schema='test_schema')
    op.create_table('equipo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('jugador_id', sa.Integer(), nullable=True),
    sa.Column('jugador2_id', sa.Integer(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['test_schema.categoria.id'], ),
    sa.ForeignKeyConstraint(['jugador2_id'], ['test_schema.jugador.id'], ),
    sa.ForeignKeyConstraint(['jugador_id'], ['test_schema.jugador.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='test_schema'
    )
    op.create_index(op.f('ix_test_schema_equipo_id'), 'equipo', ['id'], unique=False, schema='test_schema')
    op.create_table('inscripcion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jugador_id', sa.Integer(), nullable=True),
    sa.Column('equipo_id', sa.Integer(), nullable=True),
    sa.Column('torneo_categoria_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['equipo_id'], ['test_schema.equipo.id'], ),
    sa.ForeignKeyConstraint(['jugador_id'], ['test_schema.jugador.id'], ),
    sa.ForeignKeyConstraint(['torneo_categoria_id'], ['test_schema.torneo_categoria.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='test_schema'
    )
    op.create_index(op.f('ix_test_schema_inscripcion_id'), 'inscripcion', ['id'], unique=False, schema='test_schema')
    op.create_table('partido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('horario', sa.Time(), nullable=False),
    sa.Column('equipo1_id', sa.Integer(), nullable=True),
    sa.Column('equipo2_id', sa.Integer(), nullable=True),
    sa.Column('equipo_ganador_id', sa.Integer(), nullable=True),
    sa.Column('jugador1_id', sa.Integer(), nullable=True),
    sa.Column('jugador2_id', sa.Integer(), nullable=True),
    sa.Column('jugador_ganador_id', sa.Integer(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('mesa_id', sa.Integer(), nullable=True),
    sa.Column('fase_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['test_schema.categoria.id'], ),
    sa.ForeignKeyConstraint(['equipo1_id'], ['test_schema.equipo.id'], ),
    sa.ForeignKeyConstraint(['equipo2_id'], ['test_schema.equipo.id'], ),
    sa.ForeignKeyConstraint(['equipo_ganador_id'], ['test_schema.equipo.id'], ),
    sa.ForeignKeyConstraint(['fase_id'], ['test_schema.fase.id'], ),
    sa.ForeignKeyConstraint(['jugador1_id'], ['test_schema.jugador.id'], ),
    sa.ForeignKeyConstraint(['jugador2_id'], ['test_schema.jugador.id'], ),
    sa.ForeignKeyConstraint(['jugador_ganador_id'], ['test_schema.jugador.id'], ),
    sa.ForeignKeyConstraint(['mesa_id'], ['test_schema.mesa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='test_schema'
    )
    op.create_index(op.f('ix_test_schema_partido_id'), 'partido', ['id'], unique=False, schema='test_schema')
    op.create_table('set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_Set', sa.Integer(), nullable=False),
    sa.Column('puntos_Jugador1', sa.Integer(), nullable=False),
    sa.Column('puntos_Jugador2', sa.Integer(), nullable=False),
    sa.Column('partido_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['partido_id'], ['test_schema.partido.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='test_schema'
    )
    op.create_index(op.f('ix_test_schema_set_id'), 'set', ['id'], unique=False, schema='test_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_schema_set_id'), table_name='set', schema='test_schema')
    op.drop_table('set', schema='test_schema')
    op.drop_index(op.f('ix_test_schema_partido_id'), table_name='partido', schema='test_schema')
    op.drop_table('partido', schema='test_schema')
    op.drop_index(op.f('ix_test_schema_inscripcion_id'), table_name='inscripcion', schema='test_schema')
    op.drop_table('inscripcion', schema='test_schema')
    op.drop_index(op.f('ix_test_schema_equipo_id'), table_name='equipo', schema='test_schema')
    op.drop_table('equipo', schema='test_schema')
    op.drop_index(op.f('ix_test_schema_jugador_id'), table_name='jugador', schema='test_schema')
    op.drop_table('jugador', schema='test_schema')
    op.drop_index(op.f('ix_test_schema_fase_id'), table_name='fase', schema='test_schema')
    op.drop_table('fase', schema='test_schema')
    op.drop_index(op.f('ix_test_schema_asociacion_id'), table_name='asociacion', schema='test_schema')
    op.drop_table('asociacion', schema='test_schema')
    op.drop_index(op.f('ix_test_schema_torneo_categoria_id'), table_name='torneo_categoria', schema='test_schema')
    op.drop_table('torneo_categoria', schema='test_schema')
    op.drop_table('mesa', schema='test_schema')
    op.drop_index(op.f('ix_test_schema_ciudad_id'), table_name='ciudad', schema='test_schema')
    op.drop_table('ciudad', schema='test_schema')
    op.drop_index(op.f('ix_test_schema_torneo_id'), table_name='torneo', schema='test_schema')
    op.drop_table('torneo', schema='test_schema')
    op.drop_index(op.f('ix_test_schema_pais_id'), table_name='pais', schema='test_schema')
    op.drop_table('pais', schema='test_schema')
    op.drop_index(op.f('ix_test_schema_genero_id'), table_name='genero', schema='test_schema')
    op.drop_table('genero', schema='test_schema')
    op.drop_index(op.f('ix_test_schema_categoria_id'), table_name='categoria', schema='test_schema')
    op.drop_table('categoria', schema='test_schema')
    # ### end Alembic commands ###
