"""mis tablitas nurin

Revision ID: cad9f822d372
Revises: b5b7d0e12565
Create Date: 2025-07-05 22:12:12.526418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cad9f822d372'
down_revision: Union[str, None] = 'b5b7d0e12565'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('edad_Min', sa.Integer(), nullable=True),
    sa.Column('edad_Max', sa.Integer(), nullable=True),
    sa.Column('genero', sa.String(), nullable=False),
    sa.Column('set_por_partido', sa.Integer(), nullable=True),
    sa.Column('puntos_por_set', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='hola_andres'
    )
    op.create_index(op.f('ix_hola_andres_categoria_id'), 'categoria', ['id'], unique=False, schema='hola_andres')
    op.create_table('genero',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='hola_andres'
    )
    op.create_index(op.f('ix_hola_andres_genero_id'), 'genero', ['id'], unique=False, schema='hola_andres')
    op.create_table('pais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='hola_andres'
    )
    op.create_index(op.f('ix_hola_andres_pais_id'), 'pais', ['id'], unique=False, schema='hola_andres')
    op.create_table('torneo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('fecha_Inscripcion', sa.Date(), nullable=False),
    sa.Column('competencia', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='hola_andres'
    )
    op.create_index(op.f('ix_hola_andres_torneo_id'), 'torneo', ['id'], unique=False, schema='hola_andres')
    op.create_table('ciudad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('pais_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['pais_id'], ['hola_andres.pais.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='hola_andres'
    )
    op.create_index(op.f('ix_hola_andres_ciudad_id'), 'ciudad', ['id'], unique=False, schema='hola_andres')
    op.create_table('mesa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Torneo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Torneo_id'], ['hola_andres.torneo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='hola_andres'
    )
    op.create_table('torneo_categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('torneo_id', sa.Integer(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['hola_andres.categoria.id'], ),
    sa.ForeignKeyConstraint(['torneo_id'], ['hola_andres.torneo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='hola_andres'
    )
    op.create_index(op.f('ix_hola_andres_torneo_categoria_id'), 'torneo_categoria', ['id'], unique=False, schema='hola_andres')
    op.create_table('asociacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('ciudad', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ciudad'], ['hola_andres.ciudad.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='hola_andres'
    )
    op.create_index(op.f('ix_hola_andres_asociacion_id'), 'asociacion', ['id'], unique=False, schema='hola_andres')
    op.create_table('fase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('torneo_categoria_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['torneo_categoria_id'], ['hola_andres.torneo_categoria.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='hola_andres'
    )
    op.create_index(op.f('ix_hola_andres_fase_id'), 'fase', ['id'], unique=False, schema='hola_andres')
    op.create_table('jugador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('genero', sa.Integer(), nullable=True),
    sa.Column('ciudad', sa.Integer(), nullable=True),
    sa.Column('asociacion_id', sa.Integer(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asociacion_id'], ['hola_andres.asociacion.id'], ),
    sa.ForeignKeyConstraint(['categoria_id'], ['hola_andres.categoria.id'], ),
    sa.ForeignKeyConstraint(['ciudad'], ['hola_andres.ciudad.id'], ),
    sa.ForeignKeyConstraint(['genero'], ['hola_andres.genero.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='hola_andres'
    )
    op.create_index(op.f('ix_hola_andres_jugador_id'), 'jugador', ['id'], unique=False, schema='hola_andres')
    op.create_table('equipo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('jugador_id', sa.Integer(), nullable=True),
    sa.Column('jugador2_id', sa.Integer(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['hola_andres.categoria.id'], ),
    sa.ForeignKeyConstraint(['jugador2_id'], ['hola_andres.jugador.id'], ),
    sa.ForeignKeyConstraint(['jugador_id'], ['hola_andres.jugador.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='hola_andres'
    )
    op.create_index(op.f('ix_hola_andres_equipo_id'), 'equipo', ['id'], unique=False, schema='hola_andres')
    op.create_table('inscripcion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jugador_id', sa.Integer(), nullable=True),
    sa.Column('equipo_id', sa.Integer(), nullable=True),
    sa.Column('torneo_categoria_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['equipo_id'], ['hola_andres.equipo.id'], ),
    sa.ForeignKeyConstraint(['jugador_id'], ['hola_andres.jugador.id'], ),
    sa.ForeignKeyConstraint(['torneo_categoria_id'], ['hola_andres.torneo_categoria.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='hola_andres'
    )
    op.create_index(op.f('ix_hola_andres_inscripcion_id'), 'inscripcion', ['id'], unique=False, schema='hola_andres')
    op.create_table('partido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('horario', sa.Time(), nullable=False),
    sa.Column('equipo1_id', sa.Integer(), nullable=True),
    sa.Column('equipo2_id', sa.Integer(), nullable=True),
    sa.Column('equipo_ganador_id', sa.Integer(), nullable=True),
    sa.Column('jugador1_id', sa.Integer(), nullable=True),
    sa.Column('jugador2_id', sa.Integer(), nullable=True),
    sa.Column('jugador_ganador_id', sa.Integer(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('mesa_id', sa.Integer(), nullable=True),
    sa.Column('fase_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['hola_andres.categoria.id'], ),
    sa.ForeignKeyConstraint(['equipo1_id'], ['hola_andres.equipo.id'], ),
    sa.ForeignKeyConstraint(['equipo2_id'], ['hola_andres.equipo.id'], ),
    sa.ForeignKeyConstraint(['equipo_ganador_id'], ['hola_andres.equipo.id'], ),
    sa.ForeignKeyConstraint(['fase_id'], ['hola_andres.fase.id'], ),
    sa.ForeignKeyConstraint(['jugador1_id'], ['hola_andres.jugador.id'], ),
    sa.ForeignKeyConstraint(['jugador2_id'], ['hola_andres.jugador.id'], ),
    sa.ForeignKeyConstraint(['jugador_ganador_id'], ['hola_andres.jugador.id'], ),
    sa.ForeignKeyConstraint(['mesa_id'], ['hola_andres.mesa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='hola_andres'
    )
    op.create_index(op.f('ix_hola_andres_partido_id'), 'partido', ['id'], unique=False, schema='hola_andres')
    op.create_table('set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_Set', sa.Integer(), nullable=False),
    sa.Column('puntos_Jugador1', sa.Integer(), nullable=False),
    sa.Column('puntos_Jugador2', sa.Integer(), nullable=False),
    sa.Column('partido_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['partido_id'], ['hola_andres.partido.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='hola_andres'
    )
    op.create_index(op.f('ix_hola_andres_set_id'), 'set', ['id'], unique=False, schema='hola_andres')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hola_andres_set_id'), table_name='set', schema='hola_andres')
    op.drop_table('set', schema='hola_andres')
    op.drop_index(op.f('ix_hola_andres_partido_id'), table_name='partido', schema='hola_andres')
    op.drop_table('partido', schema='hola_andres')
    op.drop_index(op.f('ix_hola_andres_inscripcion_id'), table_name='inscripcion', schema='hola_andres')
    op.drop_table('inscripcion', schema='hola_andres')
    op.drop_index(op.f('ix_hola_andres_equipo_id'), table_name='equipo', schema='hola_andres')
    op.drop_table('equipo', schema='hola_andres')
    op.drop_index(op.f('ix_hola_andres_jugador_id'), table_name='jugador', schema='hola_andres')
    op.drop_table('jugador', schema='hola_andres')
    op.drop_index(op.f('ix_hola_andres_fase_id'), table_name='fase', schema='hola_andres')
    op.drop_table('fase', schema='hola_andres')
    op.drop_index(op.f('ix_hola_andres_asociacion_id'), table_name='asociacion', schema='hola_andres')
    op.drop_table('asociacion', schema='hola_andres')
    op.drop_index(op.f('ix_hola_andres_torneo_categoria_id'), table_name='torneo_categoria', schema='hola_andres')
    op.drop_table('torneo_categoria', schema='hola_andres')
    op.drop_table('mesa', schema='hola_andres')
    op.drop_index(op.f('ix_hola_andres_ciudad_id'), table_name='ciudad', schema='hola_andres')
    op.drop_table('ciudad', schema='hola_andres')
    op.drop_index(op.f('ix_hola_andres_torneo_id'), table_name='torneo', schema='hola_andres')
    op.drop_table('torneo', schema='hola_andres')
    op.drop_index(op.f('ix_hola_andres_pais_id'), table_name='pais', schema='hola_andres')
    op.drop_table('pais', schema='hola_andres')
    op.drop_index(op.f('ix_hola_andres_genero_id'), table_name='genero', schema='hola_andres')
    op.drop_table('genero', schema='hola_andres')
    op.drop_index(op.f('ix_hola_andres_categoria_id'), table_name='categoria', schema='hola_andres')
    op.drop_table('categoria', schema='hola_andres')
    # ### end Alembic commands ###
