"""Test Primera tabla

Revision ID: e3506fd03a67
Revises: 818d54107b4b
Create Date: 2025-06-14 22:57:50.478625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3506fd03a67'
down_revision: Union[str, None] = '818d54107b4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Asociacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('ciudad', sa.String(), nullable=False),
    sa.Column('pais', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='test_schema'
    )
    op.create_index(op.f('ix_test_schema_Asociacion_id'), 'Asociacion', ['id'], unique=False, schema='test_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_schema_Asociacion_id'), table_name='Asociacion', schema='test_schema')
    op.drop_table('Asociacion', schema='test_schema')
    # ### end Alembic commands ###
